#!/usr/bin/env python3
"""Generate the OpenGL 1.1 stubs and the dglGetProcAddress table.

  gen_stubs.py SRC_DIR... OUT_DIR

Reads src/gl/gl11.api (every GL 1.1 entry point with its signature) and the
APIENTRY definitions in the given source directories, and writes:

  OUT_DIR/stubs.c  a stub for each GL 1.1 function DOS-GL does not implement:
                   it logs "DGL-STUB glName" once over COM1, counts the call in
                   DGL_STATS and returns zero (GL_FALSE, 0 or NULL); output
                   parameters are left as they are. A program that binds every
                   GL 1.1 function (Quake 2's static ref_gl) therefore links,
                   and any stub reached at run time is visible.
  OUT_DIR/procs.c  dglGetProcAddress: every GL 1.1 function and every
                   extension function (names ending ARB, EXT or SGIS) the
                   sources define, plus the core names later GL versions
                   gave some of them (multitexture, buffer objects,
                   glDrawRangeElements), sorted for a binary search.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# Extension functions later versions made core under the name without the
# suffix: GL 1.2's glDrawRangeElements, 1.3's ARB_multitexture, 1.5's
# ARB_vertex_buffer_object.
CORE = re.compile(r"^gl((ActiveTexture|ClientActiveTexture|MultiTexCoord[1-4][dfis]v?|BindBuffer|DeleteBuffers|"
                  r"GenBuffers|IsBuffer|BufferData|BufferSubData|GetBufferSubData|MapBuffer|UnmapBuffer|"
                  r"GetBufferParameteriv|GetBufferPointerv)ARB|DrawRangeElementsEXT)$")
API = os.path.join(os.path.dirname(HERE), "src", "gl", "gl11.api")


def write(path, lines):
    text = "\n".join(lines) + "\n"
    if os.path.exists(path) and open(path).read() == text:
        return
    with open(path, "w") as f:
        f.write(text)


def main():
    *dirs, out = sys.argv[1:]
    have = set()
    for d in dirs:
        for name in sorted(os.listdir(d)):
            if name.endswith(".c"):
                have |= set(re.findall(r"APIENTRY\s+(gl[A-Z]\w*)\s*\(", open(os.path.join(d, name)).read()))
    api = []
    for line in open(API):
        if line.startswith("#") or not line.strip():
            continue
        api.append(tuple(x.strip() for x in line.split("|")))
    missing = [row for row in api if row[0] not in have]
    os.makedirs(out, exist_ok=True)

    lines = ["/* GENERATED by tools/gen_stubs.py from src/gl/gl11.api - do not edit.",
             " * The OpenGL 1.1 functions DOS-GL does not implement: each logs",
             " * DGL-STUB once, counts the call and returns zero. */",
             "#include <GL/gl.h>", "#include <GL/glext.h>", "",
             "void dgl_stub_hit(const char *name, int *seen);", ""]
    for name, ret, params in missing:
        types = [p.strip() for p in params.split(",")] if params not in ("void", "") else []
        args = ", ".join("%s a%d" % (t, i) for i, t in enumerate(types)) or "void"
        uses = "".join(" (void)a%d;" % i for i in range(len(types)))
        body = "static int seen;%s dgl_stub_hit(\"%s\", &seen);" % (uses, name)
        tail = "" if ret == "void" else " return 0;"
        lines.append("%s APIENTRY %s(%s) { %s%s }" % (ret, name, args, body, tail))
    write(os.path.join(out, "stubs.c"), lines)

    # The table's translation unit leaves out GL/gl.h: each function is
    # declared with a placeholder type, only its address is taken.
    procs = sorted(set(r[0] for r in api) | set(n for n in have if re.search(r"(ARB|EXT|SGIS)$", n)))
    # Functions that became core also answer to their core names, which
    # renderers written for later versions ask for first (Xash3D's)
    entries = sorted([(n, n) for n in procs] +
                     [(n[:-3], n) for n in procs if CORE.match(n)])
    lines = ["/* GENERATED by tools/gen_stubs.py - do not edit.",
             " * dglGetProcAddress: GL 1.1, the extension functions DOS-GL defines, and",
             " * the core names of those later GL versions adopted. */",
             "#include <GL/dosgl.h>", "#include <stdlib.h>", "#include <string.h>", ""]
    lines += ["void %s(void);" % n for n in procs]
    lines += ["", "static const struct { const char *name; void (*fn)(void); } procs[] = {"]
    lines += ["    { \"%s\", %s }," % e for e in entries]
    lines += ["};", "",
              "static int cmp(const void *key, const void *elem)",
              "{",
              "    return strcmp((const char *)key, *(const char *const *)elem);",
              "}", "",
              "void *dglGetProcAddress(const char *name)",
              "{",
              "    const void *p = name ? bsearch(name, procs, sizeof procs / sizeof procs[0], sizeof procs[0], cmp) : NULL;",
              "    return p ? (void *)((const __typeof__(procs[0]) *)p)->fn : NULL;",
              "}"]
    write(os.path.join(out, "procs.c"), lines)
    print("gen_stubs: %d of %d GL 1.1 functions stubbed, %d in the proc table" % (len(missing), len(api), len(entries)))


if __name__ == "__main__":
    main()
